apiVersion: v1
kind: Service
metadata:
  name: {{ include "voting-app.fullname" . }}-vote
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
    app: vote
spec:
  selector:
    app: vote
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "voting-app.fullname" . }}-vote-external
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
    app: vote
spec:
  selector:
    app: vote
  ports:
  - name: http
    port: {{ .Values.vote.service.port }}
    targetPort: 80
  type: {{ .Values.vote.service.type }}
